// ================================================================
// NIFTY 150+ STOCK UNIVERSE — ported from StockSense Pro v4
// ================================================================

const UNIVERSE = [
  { s: 'RELIANCE', n: 'Reliance Industries', sec: 'Energy' },
  { s: 'TCS', n: 'Tata Consultancy Services', sec: 'IT' },
  { s: 'HDFCBANK', n: 'HDFC Bank', sec: 'Banking' },
  { s: 'INFY', n: 'Infosys', sec: 'IT' },
  { s: 'ICICIBANK', n: 'ICICI Bank', sec: 'Banking' },
  { s: 'HINDUNILVR', n: 'Hindustan Unilever', sec: 'FMCG' },
  { s: 'ITC', n: 'ITC Limited', sec: 'FMCG' },
  { s: 'BHARTIARTL', n: 'Bharti Airtel', sec: 'Telecom' },
  { s: 'SBIN', n: 'State Bank of India', sec: 'Banking' },
  { s: 'BAJFINANCE', n: 'Bajaj Finance', sec: 'Finance' },
  { s: 'LT', n: 'Larsen & Toubro', sec: 'Infra' },
  { s: 'HCLTECH', n: 'HCL Technologies', sec: 'IT' },
  { s: 'WIPRO', n: 'Wipro', sec: 'IT' },
  { s: 'TATAMOTORS', n: 'Tata Motors', sec: 'Auto' },
  { s: 'AXISBANK', n: 'Axis Bank', sec: 'Banking' },
  { s: 'SUNPHARMA', n: 'Sun Pharmaceutical', sec: 'Pharma' },
  { s: 'MARUTI', n: 'Maruti Suzuki', sec: 'Auto' },
  { s: 'NTPC', n: 'NTPC Limited', sec: 'Power' },
  { s: 'TITAN', n: 'Titan Company', sec: 'FMCG' },
  { s: 'ADANIENT', n: 'Adani Enterprises', sec: 'Energy' },
  { s: 'ADANIPORTS', n: 'Adani Ports', sec: 'Infra' },
  { s: 'ULTRACEMCO', n: 'UltraTech Cement', sec: 'Cement' },
  { s: 'TECHM', n: 'Tech Mahindra', sec: 'IT' },
  { s: 'NESTLEIND', n: 'Nestle India', sec: 'FMCG' },
  { s: 'POWERGRID', n: 'Power Grid Corp', sec: 'Power' },
  { s: 'COALINDIA', n: 'Coal India', sec: 'Energy' },
  { s: 'KOTAKBANK', n: 'Kotak Mahindra Bank', sec: 'Banking' },
  { s: 'TATASTEEL', n: 'Tata Steel', sec: 'Metal' },
  { s: 'JSWSTEEL', n: 'JSW Steel', sec: 'Metal' },
  { s: 'HINDALCO', n: 'Hindalco Industries', sec: 'Metal' },
  { s: 'BAJAJFINSV', n: 'Bajaj Finserv', sec: 'Finance' },
  { s: 'DRREDDY', n: "Dr. Reddy's Labs", sec: 'Pharma' },
  { s: 'CIPLA', n: 'Cipla', sec: 'Pharma' },
  { s: 'ASIANPAINT', n: 'Asian Paints', sec: 'FMCG' },
  { s: 'APOLLOHOSP', n: 'Apollo Hospitals', sec: 'Pharma' },
  { s: 'HEROMOTOCO', n: 'Hero MotoCorp', sec: 'Auto' },
  { s: 'BAJAJ-AUTO', n: 'Bajaj Auto', sec: 'Auto' },
  { s: 'EICHERMOT', n: 'Eicher Motors', sec: 'Auto' },
  { s: 'INDUSINDBK', n: 'IndusInd Bank', sec: 'Banking' },
  { s: 'GRASIM', n: 'Grasim Industries', sec: 'Cement' },
  { s: 'M&M', n: 'Mahindra & Mahindra', sec: 'Auto' },
  { s: 'ONGC', n: 'Oil & Natural Gas', sec: 'Energy' },
  { s: 'BRITANNIA', n: 'Britannia Industries', sec: 'FMCG' },
  { s: 'TATACONSUM', n: 'Tata Consumer Products', sec: 'FMCG' },
  { s: 'BPCL', n: 'Bharat Petroleum', sec: 'Energy' },
  { s: 'DIVISLAB', n: 'Divis Laboratories', sec: 'Pharma' },
  { s: 'LTIM', n: 'LTIMindtree', sec: 'IT' },
  { s: 'HAL', n: 'Hindustan Aeronautics', sec: 'Infra' },
  { s: 'BEL', n: 'Bharat Electronics', sec: 'Infra' },
  { s: 'TRENT', n: 'Trent', sec: 'FMCG' },
  { s: 'ADANIGREEN', n: 'Adani Green Energy', sec: 'Power' },
  { s: 'AMBUJACEM', n: 'Ambuja Cements', sec: 'Cement' },
  { s: 'AUROPHARMA', n: 'Aurobindo Pharma', sec: 'Pharma' },
  { s: 'BANKBARODA', n: 'Bank of Baroda', sec: 'Banking' },
  { s: 'BHEL', n: 'Bharat Heavy Electricals', sec: 'Infra' },
  { s: 'BOSCHLTD', n: 'Bosch', sec: 'Auto' },
  { s: 'CANBK', n: 'Canara Bank', sec: 'Banking' },
  { s: 'CHOLAFIN', n: 'Cholamandalam Fin', sec: 'Finance' },
  { s: 'COLPAL', n: 'Colgate-Palmolive', sec: 'FMCG' },
  { s: 'DLF', n: 'DLF', sec: 'Realty' },
  { s: 'GAIL', n: 'GAIL India', sec: 'Energy' },
  { s: 'GODREJCP', n: 'Godrej Consumer', sec: 'FMCG' },
  { s: 'HAVELLS', n: 'Havells India', sec: 'FMCG' },
  { s: 'HDFCAMC', n: 'HDFC AMC', sec: 'Finance' },
  { s: 'HDFCLIFE', n: 'HDFC Life Insurance', sec: 'Finance' },
  { s: 'ICICIPRULI', n: 'ICICI Pru Life', sec: 'Finance' },
  { s: 'IGL', n: 'Indraprastha Gas', sec: 'Energy' },
  { s: 'INDHOTEL', n: 'Indian Hotels', sec: 'FMCG' },
  { s: 'INDUSTOWER', n: 'Indus Towers', sec: 'Telecom' },
  { s: 'IRCTC', n: 'IRCTC', sec: 'Infra' },
  { s: 'JINDALSTEL', n: 'Jindal Steel & Power', sec: 'Metal' },
  { s: 'LUPIN', n: 'Lupin', sec: 'Pharma' },
  { s: 'MARICO', n: 'Marico', sec: 'FMCG' },
  { s: 'MOTHERSON', n: 'Motherson Sumi', sec: 'Auto' },
  { s: 'MUTHOOTFIN', n: 'Muthoot Finance', sec: 'Finance' },
  { s: 'NAUKRI', n: 'Info Edge (Naukri)', sec: 'IT' },
  { s: 'NHPC', n: 'NHPC', sec: 'Power' },
  { s: 'OBEROIRLTY', n: 'Oberoi Realty', sec: 'Realty' },
  { s: 'PFC', n: 'Power Finance Corp', sec: 'Finance' },
  { s: 'PIDILITIND', n: 'Pidilite Industries', sec: 'FMCG' },
  { s: 'PNB', n: 'Punjab National Bank', sec: 'Banking' },
  { s: 'POLYCAB', n: 'Polycab India', sec: 'Infra' },
  { s: 'RECLTD', n: 'REC Limited', sec: 'Finance' },
  { s: 'SBICARD', n: 'SBI Cards', sec: 'Finance' },
  { s: 'SBILIFE', n: 'SBI Life Insurance', sec: 'Finance' },
  { s: 'SHREECEM', n: 'Shree Cement', sec: 'Cement' },
  { s: 'SIEMENS', n: 'Siemens', sec: 'Infra' },
  { s: 'TATAPOWER', n: 'Tata Power', sec: 'Power' },
  { s: 'TORNTPHARM', n: 'Torrent Pharma', sec: 'Pharma' },
  { s: 'ZOMATO', n: 'Zomato', sec: 'IT' },
  { s: 'ABB', n: 'ABB India', sec: 'Infra' },
  { s: 'ACC', n: 'ACC Cements', sec: 'Cement' },
  { s: 'ASTRAL', n: 'Astral', sec: 'Infra' },
  { s: 'AUBANK', n: 'AU Small Finance Bank', sec: 'Banking' },
  { s: 'BALKRISIND', n: 'Balkrishna Industries', sec: 'Auto' },
  { s: 'BANDHANBNK', n: 'Bandhan Bank', sec: 'Banking' },
  { s: 'BATAINDIA', n: 'Bata India', sec: 'FMCG' },
  { s: 'BERGEPAINT', n: 'Berger Paints', sec: 'FMCG' },
  { s: 'BHARATFORG', n: 'Bharat Forge', sec: 'Auto' },
  { s: 'BIOCON', n: 'Biocon', sec: 'Pharma' },
  { s: 'COFORGE', n: 'Coforge', sec: 'IT' },
  { s: 'CONCOR', n: 'Container Corp', sec: 'Infra' },
  { s: 'CROMPTON', n: 'Crompton Greaves', sec: 'FMCG' },
  { s: 'CUMMINSIND', n: 'Cummins India', sec: 'Infra' },
  { s: 'DABUR', n: 'Dabur India', sec: 'FMCG' },
  { s: 'DMART', n: 'Avenue Supermarts', sec: 'FMCG' },
  { s: 'ESCORTS', n: 'Escorts Kubota', sec: 'Auto' },
  { s: 'FEDERALBNK', n: 'Federal Bank', sec: 'Banking' },
  { s: 'FORTIS', n: 'Fortis Healthcare', sec: 'Pharma' },
  { s: 'GODREJPROP', n: 'Godrej Properties', sec: 'Realty' },
  { s: 'HINDPETRO', n: 'Hindustan Petroleum', sec: 'Energy' },
  { s: 'IDFCFIRSTB', n: 'IDFC First Bank', sec: 'Banking' },
  { s: 'INDIANB', n: 'Indian Bank', sec: 'Banking' },
  { s: 'IOC', n: 'Indian Oil Corp', sec: 'Energy' },
  { s: 'IRFC', n: 'Indian Railway Finance', sec: 'Finance' },
  { s: 'JUBLFOOD', n: 'Jubilant FoodWorks', sec: 'FMCG' },
  { s: 'KPITTECH', n: 'KPIT Technologies', sec: 'IT' },
  { s: 'LICHSGFIN', n: 'LIC Housing Finance', sec: 'Finance' },
  { s: 'LTTS', n: 'L&T Technology Services', sec: 'IT' },
  { s: 'MANAPPURAM', n: 'Manappuram Finance', sec: 'Finance' },
  { s: 'MGL', n: 'Mahanagar Gas', sec: 'Energy' },
  { s: 'MPHASIS', n: 'Mphasis', sec: 'IT' },
  { s: 'PAGEIND', n: 'Page Industries', sec: 'FMCG' },
  { s: 'PERSISTENT', n: 'Persistent Systems', sec: 'IT' },
  { s: 'PETRONET', n: 'Petronet LNG', sec: 'Energy' },
  { s: 'PIIND', n: 'PI Industries', sec: 'Pharma' },
  { s: 'SRF', n: 'SRF', sec: 'FMCG' },
  { s: 'SAIL', n: 'Steel Authority of India', sec: 'Metal' },
  { s: 'SUZLON', n: 'Suzlon Energy', sec: 'Power' },
  { s: 'TVSMOTOR', n: 'TVS Motor Company', sec: 'Auto' },
  { s: 'VOLTAS', n: 'Voltas', sec: 'FMCG' },
  { s: 'JSWENERGY', n: 'JSW Energy', sec: 'Power' },
  { s: 'RVNL', n: 'Rail Vikas Nigam', sec: 'Infra' },
  { s: 'HUDCO', n: 'HUDCO', sec: 'Finance' },
  { s: 'PRESTIGE', n: 'Prestige Estates', sec: 'Realty' },
  { s: 'LODHA', n: 'Macrotech Developers', sec: 'Realty' },
  { s: 'TATAELXSI', n: 'Tata Elxsi', sec: 'IT' },
  { s: 'TATACHEM', n: 'Tata Chemicals', sec: 'Energy' },
  { s: 'UNIONBANK', n: 'Union Bank of India', sec: 'Banking' },
  { s: 'IDEA', n: 'Vodafone Idea', sec: 'Telecom' },
  { s: 'PAYTM', n: 'One97 Communications', sec: 'IT' },
];

module.exports = { UNIVERSE };
